[package]
name = "advent-of-code-2021-rust"
version = "0.1.0"
edition = "2021"
authors = ["Carter David Henning"]
summary = "Advent of Code 2021 solutions in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
